### ISSUE TITLE
Unable to edit a shelf if the description is empty

### ISSUE THREAD

**Issue by PtiBzh** [inventaire/inventaire-client#231] opened 2020-10-30 21:26 UTC
I get the error message "invalid description: null" when trying to save an edit shelf without a description

**Comment by maxlath** [comment] 2020-10-31 08:24
This is a duplicate of https://github.com/inventaire/inventaire/issues/437, so I'm closing in favor of the older one.
Thank for reporting!

**Closed by maxlath** 2020-10-31 08:24 UTC
